# 站点配置
site:
  title: "StaticSiteMenu"
  description: "您的个人网站导航中心，提供精选网站分类、快速访问和个性化收藏功能，让您的网络浏览更加高效便捷。"
  keywords: "网站导航,网址导航,网站收藏,网站分类,快速访问,个人导航,网络导航,网站大全,网址大全,网站推荐"
  author: "M.Talen"
  language: "zh-CN"
  favicon: "/favicon.png"

# 关于页面
about:
  # 社交媒体
  social:
    - name: Email
      url: mailto:talen2004@163.com
      url_text: "talen2004@163.com"
      icon: "fas fa-envelope"
    - name: 微信
      url_text: "f18596373623"
      icon: "fab fa-weixin"
      copy: true
    - name: X
      url: https://x.com/Talen_Flec
      url_text: "@Talen_Flec"
      icon: "fab fa-twitter"

  # 订阅关注
  follow:
    - name: Github
      url: "https://github.com/talen8"
      icon: "fab fa-github"
      color: "#000000"
    - name: Twitter
      url: "https://twitter.com/flecnav"
      icon: "fab fa-twitter"
      color: "#000000"
    - name: 微信公众号
      url: "#"
      icon: "fab fa-weixin"
      color: "#000000"
    - name: Bilibili
      url: "https://space.bilibili.com/479887195/"
      icon: "fab fa-bilibili"
      color: "#000000"
  
  # 赞赏方式
  reward:
    - name: 微信
      img: "/images/reward/rewardWechatQR.png"
    - name: 支付宝
      img: "/images/reward/rewardAlipayQR.png"
    - name: 爱发电
      img: "/images/reward/rewardAfdianQR.png"

# 页脚展示
footer:
  copyright_runtime: 2025
  powered_by: "FlecMENU"
  friendly_links:
    enable: true
    quantity: 5
  links:
    - name: 鲁ICP备2023049269号
      url: https://beian.miit.gov.cn/
    - name: 鲁公网安备37088102000500号
      url: http://www.beian.gov.cn/portal/registerSystemInfo?recordcode=37088102000500

# 悬浮组件
floating_button:
  enable: true
  go_to_top: true
  theme_switching: true
  items:
    - name: 微信
      img: "/images/wechat.png"
      icon: "fab fa-weixin"
    - name: 邮箱
      url: mailto:talen2004@163.com
      icon: "fas fa-envelope"

# 头部导航
header:
  items:
    - name: 博客
      url: https://blog.talen.top
      icon: "fas fa-blog"
    - name: 关于
      url: /about
      icon: "fas fa-info"

# 搜索引擎
search_engine:
  - name: "百度"
    placeholder: "百度一下，你就知道"
    url: "https://www.baidu.com/s?wd="
  - name: "bing"
    placeholder: "使用 Microsoft 必应进行搜索"
    url: "https://www.bing.com/search?q="
  # - name: "google"
  #   placeholder: "Google 搜索"
  #   url: "https://www.google.com/search?q="

